{
  "hash": "58f08a63f96e76388bf8cb15311a26f4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Correlation and Regression\"\nsubtitle: \"From Measuring Association to Predicting Outcomes\"\ndescription: |\n  Quantify relationships between continuous variables using Pearson and Spearman\n  correlation. Build simple linear regression models, check assumptions, and interpret\n  R². Extend to multiple regression for confounding adjustment and logistic regression\n  for binary outcomes. Indian clinical examples throughout.\ncategories:\n  - Biostatistics\n  - Correlation\n  - Regression\n  - Linear Models\n  - Logistic Regression\nauthor: \"AIIMS Bhopal Biostatistics Course\"\ndate: \"2026-02-25\"\n---\n\n\n\n::: {.callout-note appearance=\"minimal\"}\n**Lecture slides for this module:** [Open Slides](../slides/11-correlation-regression-slides.html){target=\"_blank\"}\n:::\n\n## Learning Objectives {#learning-objectives}\n\nBy the end of this module, you will be able to:\n\n1. **Calculate and interpret** Pearson and Spearman correlation coefficients\n2. **Distinguish** correlation from causation and identify lurking variables\n3. **Fit and interpret** a simple linear regression model (slope, intercept, R²)\n4. **Check regression assumptions** using residual plots and respond to violations\n5. **Explain** confidence intervals vs. prediction intervals for regression\n6. **Understand multiple regression** as a tool for confounding adjustment\n7. **Interpret logistic regression** output (odds ratios, predicted probabilities) for binary outcomes\n8. **Navigate a decision framework** for choosing the right regression model\n\n---\n\n## Clinical Hook\n\nA research team at JIPMER, Puducherry, is studying whether higher BMI is associated with higher fasting blood sugar (FBS) in 200 adults attending a health screening camp. They plot the data and see what looks like a positive trend. But the questions cascade:\n\n1. **How strong** is the association? (Correlation)\n2. **Can we predict** FBS from BMI? (Simple linear regression)\n3. **Does the association persist** after adjusting for age and sex? (Multiple regression)\n4. If the outcome were diabetes (yes/no) rather than FBS, **what model should they use?** (Logistic regression)\n\nThis module builds each tool in sequence.\n\n---\n\n## Section 1: Correlation\n\n### 1.1 What Correlation Measures\n\nCorrelation quantifies the **strength and direction** of the *linear* relationship between two continuous variables.\n\n**In words:** As one variable goes up, does the other tend to go up (positive), go down (negative), or show no pattern (zero)?\n\n$$r = \\frac{\\sum (x_i - \\bar{x})(y_i - \\bar{y})}{\\sqrt{\\sum (x_i - \\bar{x})^2 \\cdot \\sum (y_i - \\bar{y})^2}}$$\n\n**Conceptually:** r = average of the products of standardised deviations = Covariance(x, y) / (SD_x × SD_y).\n\nRange: −1 (perfect negative) to +1 (perfect positive). r = 0 means no *linear* association.\n\n---\n\n### 1.2 Generating the Data\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 200 adults at JIPMER health camp\nn <- 200\nage <- round(rnorm(n, mean = 45, sd = 12))\nbmi <- round(rnorm(n, mean = 26, sd = 4.5), 1)\n# FBS partly driven by BMI + age + noise\nfbs <- round(80 + 1.8 * bmi + 0.5 * age + rnorm(n, sd = 15))\n\nhealth <- data.frame(\n  ID = 1:n, Age = age, BMI = bmi, FBS = fbs,\n  Sex = sample(c(\"Male\", \"Female\"), n, replace = TRUE)\n)\n\ncat(\"First 6 rows:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFirst 6 rows:\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(health)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ID Age  BMI FBS    Sex\n1  1  61 17.0 161 Female\n2  2  38 27.5 135 Female\n3  3  49 31.3 162 Female\n4  4  53 35.3 171 Female\n5  5  50 19.8 132 Female\n6  6  44 20.8 124   Male\n```\n\n\n:::\n:::\n\n\n---\n\n### 1.3 Pearson Correlation: Worked Example\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nr_bmi_fbs <- cor(health$BMI, health$FBS)\ncor_test <- cor.test(health$BMI, health$FBS)\n\nggplot(health, aes(x = BMI, y = FBS)) +\n  geom_point(alpha = 0.5, color = \"#2c3e50\") +\n  geom_smooth(method = \"lm\", se = TRUE, color = \"#e74c3c\", linewidth = 1) +\n  annotate(\"text\", x = 35, y = 85,\n           label = paste0(\"r = \", round(r_bmi_fbs, 3),\n                         \"\\np < 0.001\"),\n           fontface = \"bold\", size = 5, color = \"#e74c3c\") +\n  labs(title = \"BMI vs. Fasting Blood Sugar\",\n       subtitle = \"JIPMER Health Screening Camp, n = 200\",\n       x = \"BMI (kg/m²)\", y = \"FBS (mg/dL)\") +\n  theme_clean()\n```\n\n::: {.cell-output-display}\n![](11-correlation-regression_files/figure-html/pearson-scatter-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n**Interpretation:** r = 0.448 — a moderate positive correlation. As BMI increases, FBS tends to increase. The p-value tests H₀: ρ = 0 (no linear association in the population).\n\n:::{.callout-note title=\"Interpreting Correlation Strength\"}\n\n| |r| | Interpretation |\n|------|---------------|\n| 0.00 – 0.19 | Negligible |\n| 0.20 – 0.39 | Weak |\n| 0.40 – 0.59 | Moderate |\n| 0.60 – 0.79 | Strong |\n| 0.80 – 1.00 | Very strong |\n\nThese are rough guidelines — clinical context matters. A correlation of 0.3 between a biomarker and disease may be clinically important.\n:::\n\n---\n\n### 1.4 Spearman Rank Correlation\n\nWhen the relationship is **monotonic but not linear**, or the data are **ordinal**, use Spearman's rₛ (rank-based):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Severity score (ordinal 1-5) vs. hospital LOS\nseverity <- sample(1:5, 60, replace = TRUE, prob = c(0.15, 0.25, 0.3, 0.2, 0.1))\nlos <- severity * 2 + rpois(60, lambda = 3) + round(rexp(60, rate = 0.3))\n\nrs <- cor(severity, los, method = \"spearman\")\ncat(\"Spearman rₛ =\", round(rs, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpearman rₛ = 0.716 \n```\n\n\n:::\n:::\n\n\n:::{.callout-tip title=\"Pearson vs. Spearman\"}\n\n| Feature | Pearson (r) | Spearman (rₛ) |\n|---------|------------|---------------|\n| Relationship type | Linear | Monotonic (any shape) |\n| Data type | Continuous, roughly normal | Ordinal or skewed continuous |\n| Sensitive to outliers? | Yes — a single outlier can flip r | No — works on ranks |\n| When to use | Both variables continuous, linear scatter | Ordinal data, skewed, or outliers present |\n:::\n\n---\n\n### 1.5 Correlation ≠ Causation\n\n:::{.callout-warning title=\"The Ice-Cream-Drowning Fallacy\"}\nIn summer months, ice cream sales and drowning deaths both rise. The correlation is strong (r ≈ 0.8). Should we ban ice cream?\n\n**No.** The lurking variable is **temperature** — warm weather drives both.\n\nSources of spurious association include confounding (a third variable drives both), reverse causality (y causes x), selection bias (how the sample was chosen), and measurement error.\n\nA strong r tells you the variables *move together*, not that one *causes* the other.\n:::\n\n---\n\n## Section 2: Simple Linear Regression\n\n### 2.1 The Model\n\nWe want to **predict** FBS from BMI. Simple linear regression fits the equation:\n\n**In words:** Predicted outcome = Baseline level + (Rate of change × Predictor) + Random error\n\n$$y = \\beta_0 + \\beta_1 x + \\varepsilon$$\n\nwhere:\n\n- $\\beta_0$ = **intercept** (predicted y when x = 0)\n- $\\beta_1$ = **slope** (change in y for each 1-unit increase in x)\n- $\\varepsilon$ = random error (what the model can't explain)\n\nThe method of **least squares** finds $\\beta_0$ and $\\beta_1$ that minimise $\\sum (y_i - \\hat{y}_i)^2$.\n\n---\n\n### 2.2 Fitting the Model in R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel <- lm(FBS ~ BMI, data = health)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = FBS ~ BMI, data = health)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-41.940 -11.390   0.357  10.531  48.106 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  98.1466     7.2100  13.613  < 2e-16 ***\nBMI           1.9281     0.2732   7.058 2.78e-11 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 16.42 on 198 degrees of freedom\nMultiple R-squared:  0.201,\tAdjusted R-squared:  0.197 \nF-statistic: 49.81 on 1 and 198 DF,  p-value: 2.784e-11\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncoefs <- tidy(model, conf.int = TRUE)\nb0 <- coefs$estimate[1]\nb1 <- coefs$estimate[2]\n\ncat(\"Regression equation:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRegression equation:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"FBS =\", round(b0, 2), \"+\", round(b1, 2), \"× BMI\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFBS = 98.15 + 1.93 × BMI\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nInterpretation:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nInterpretation:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"For each 1 kg/m² increase in BMI, FBS increases by\",\n    round(b1, 2), \"mg/dL on average.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFor each 1 kg/m² increase in BMI, FBS increases by 1.93 mg/dL on average.\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% CI for slope:\", round(coefs$conf.low[2], 2),\n    \"to\", round(coefs$conf.high[2], 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI for slope: 1.39 to 2.47 \n```\n\n\n:::\n:::\n\n\n:::{.callout-note title=\"Interpreting the Slope\"}\nThe slope $\\beta_1$ = 1.93 means: **for every additional 1 kg/m² of BMI, fasting blood sugar increases by about 1.9 mg/dL**, holding nothing else constant.\n\nThe intercept $\\beta_0$ = 98.1 is the predicted FBS when BMI = 0 — biologically meaningless here, but mathematically necessary to position the line.\n:::\n\n---\n\n### 2.3 Visualising the Regression\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(health, aes(x = BMI, y = FBS)) +\n  geom_point(alpha = 0.4, color = \"#2c3e50\") +\n  geom_smooth(method = \"lm\", se = TRUE, color = \"#e74c3c\", fill = \"#e74c3c\",\n              alpha = 0.15, linewidth = 1) +\n  annotate(\"text\", x = 36, y = 90,\n           label = paste0(\"FBS = \", round(b0, 1), \" + \",\n                         round(b1, 1), \" × BMI\\nR² = \",\n                         round(summary(model)$r.squared, 3)),\n           fontface = \"bold\", color = \"#e74c3c\", size = 4.5) +\n  labs(title = \"Simple Linear Regression: BMI → FBS\",\n       subtitle = \"Shaded band = 95% confidence interval for the mean\",\n       x = \"BMI (kg/m²)\", y = \"Fasting Blood Sugar (mg/dL)\") +\n  theme_clean()\n```\n\n::: {.cell-output-display}\n![](11-correlation-regression_files/figure-html/regression-plot-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n---\n\n### 2.4 R²: How Much Variance Is Explained?\n\n**In words:** R² tells you what fraction of the total scatter in y is \"explained\" by the regression line.\n\n$$R^2 = 1 - \\frac{\\text{Residual SS}}{\\text{Total SS}} = 1 - \\frac{\\sum(y_i - \\hat{y}_i)^2}{\\sum(y_i - \\bar{y})^2}$$\n\nFor simple regression, $R^2 = r^2$ (the square of the Pearson correlation).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nr_sq <- summary(model)$r.squared\ncat(\"R² =\", round(r_sq, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR² = 0.201 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"BMI explains\", round(r_sq * 100, 1), \"% of the variation in FBS.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBMI explains 20.1 % of the variation in FBS.\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"The remaining\", round((1 - r_sq) * 100, 1),\n    \"% is due to age, diet, genetics, measurement error, etc.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nThe remaining 79.9 % is due to age, diet, genetics, measurement error, etc.\n```\n\n\n:::\n:::\n\n\n:::{.callout-tip title=\"What Is a 'Good' R²?\"}\nThere is no universal threshold. In clinical prediction models, R² = 0.3–0.5 may be useful. In lab assays, R² > 0.95 is expected. Always ask: \"Is this model useful for the clinical question?\"\n:::\n\n---\n\n### 2.5 Confidence Interval vs. Prediction Interval\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnew_data <- data.frame(BMI = seq(16, 40, by = 0.5))\nci_pred <- predict(model, newdata = new_data, interval = \"confidence\")\npi_pred <- predict(model, newdata = new_data, interval = \"prediction\")\n\nplot_data <- data.frame(\n  BMI = new_data$BMI,\n  Fit = ci_pred[, \"fit\"],\n  CI_lower = ci_pred[, \"lwr\"], CI_upper = ci_pred[, \"upr\"],\n  PI_lower = pi_pred[, \"lwr\"], PI_upper = pi_pred[, \"upr\"]\n)\n\nggplot() +\n  geom_ribbon(data = plot_data, aes(x = BMI, ymin = PI_lower, ymax = PI_upper),\n              fill = \"#3498db\", alpha = 0.15) +\n  geom_ribbon(data = plot_data, aes(x = BMI, ymin = CI_lower, ymax = CI_upper),\n              fill = \"#e74c3c\", alpha = 0.25) +\n  geom_line(data = plot_data, aes(x = BMI, y = Fit), color = \"#2c3e50\",\n            linewidth = 1) +\n  geom_point(data = health, aes(x = BMI, y = FBS), alpha = 0.3) +\n  annotate(\"text\", x = 37, y = 170, label = \"Prediction interval\\n(single new patient)\",\n           color = \"#3498db\", fontface = \"bold\", size = 3.5) +\n  annotate(\"text\", x = 37, y = 135, label = \"Confidence interval\\n(population mean)\",\n           color = \"#e74c3c\", fontface = \"bold\", size = 3.5) +\n  labs(title = \"Confidence Interval vs. Prediction Interval\",\n       subtitle = \"CI = precision of estimated mean; PI = range for a new individual\",\n       x = \"BMI (kg/m²)\", y = \"FBS (mg/dL)\") +\n  theme_clean()\n```\n\n::: {.cell-output-display}\n![](11-correlation-regression_files/figure-html/ci-vs-pi-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::{.callout-note title=\"CI vs. PI\"}\n- **Confidence interval** (narrow, red): Where we expect the *average* FBS to lie for all people with a given BMI. It reflects uncertainty in the *regression line itself*.\n- **Prediction interval** (wide, blue): Where we expect a *single new patient's* FBS to lie. It includes both line uncertainty *and* individual variation.\n\nClinical prediction models report PIs. Research papers typically report CIs.\n:::\n\n---\n\n## Section 3: Regression Assumptions and Diagnostics\n\nThe four key assumptions (**LINE**):\n\n1. **L**inearity — the relationship between x and y is linear\n2. **I**ndependence — observations are independent\n3. **N**ormality — residuals are approximately normally distributed\n4. **E**qual variance (homoscedasticity) — spread of residuals is constant across fitted values\n\n### 3.1 Diagnostic Plots\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))\nplot(model)\n```\n\n::: {.cell-output-display}\n![](11-correlation-regression_files/figure-html/diagnostic-plots-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n**How to read these:**\n\n- **Residuals vs. Fitted:** Should be a random cloud. Patterns (curves, funnels) indicate non-linearity or heteroscedasticity.\n- **Q-Q plot:** Points should follow the diagonal. Deviations at the tails suggest non-normal residuals.\n- **Scale-Location:** Should show a roughly flat red line. An upward trend suggests increasing variance.\n- **Residuals vs. Leverage:** Points in the upper/lower right (high leverage, large residual) may be influential — check Cook's distance > 0.5.\n\n---\n\n### 3.2 What to Do When Assumptions Fail\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-bordered table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;font-weight: bold;color: white !important;background-color: rgba(30, 58, 95, 255) !important;\"> Problem </th>\n   <th style=\"text-align:left;font-weight: bold;color: white !important;background-color: rgba(30, 58, 95, 255) !important;\"> Detection </th>\n   <th style=\"text-align:left;font-weight: bold;color: white !important;background-color: rgba(30, 58, 95, 255) !important;\"> Solution </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Non-linear relationship </td>\n   <td style=\"text-align:left;\"> Curved pattern in residuals vs. fitted </td>\n   <td style=\"text-align:left;\"> Transform x or y (log, sqrt); add polynomial term </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Non-normal residuals </td>\n   <td style=\"text-align:left;\"> Deviation from diagonal on Q-Q plot </td>\n   <td style=\"text-align:left;\"> Transform y; use robust regression; often OK if n &gt; 30 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Heteroscedasticity (funnel shape) </td>\n   <td style=\"text-align:left;\"> Spread increases with fitted values </td>\n   <td style=\"text-align:left;\"> Transform y (log); use weighted least squares; robust SE </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Influential outliers </td>\n   <td style=\"text-align:left;\"> Cook's distance &gt; 0.5 or 1 </td>\n   <td style=\"text-align:left;\"> Investigate data entry errors; report results with and without </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n---\n\n## Section 4: Multiple Regression\n\n### 4.1 Why Adjust for Confounders?\n\nIn our JIPMER data, BMI and FBS are associated — but **age** also influences FBS. Is the BMI–FBS association genuine, or is it partly (or entirely) confounded by age?\n\n**Multiple regression** lets us ask: *\"What is the effect of BMI on FBS, holding age and sex constant?\"*\n\n$$\\text{FBS} = \\beta_0 + \\beta_1 \\times \\text{BMI} + \\beta_2 \\times \\text{Age} + \\beta_3 \\times \\text{Sex} + \\varepsilon$$\n\n**In words:** Each coefficient tells you the effect of that variable *while all others are held fixed*.\n\n---\n\n### 4.2 Fitting the Multiple Regression\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel_multi <- lm(FBS ~ BMI + Age + Sex, data = health)\nsummary(model_multi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = FBS ~ BMI + Age + Sex, data = health)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-39.198  -9.294  -0.238   9.588  46.001 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  74.9954     8.3993   8.929 3.12e-16 ***\nBMI           2.0149     0.2605   7.734 5.35e-13 ***\nAge           0.4315     0.0951   4.537 9.92e-06 ***\nSexMale       3.3145     2.2089   1.501    0.135    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 15.61 on 196 degrees of freedom\nMultiple R-squared:  0.2857,\tAdjusted R-squared:  0.2747 \nF-statistic: 26.13 on 3 and 196 DF,  p-value: 2.917e-14\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncoefs_simple <- tidy(model, conf.int = TRUE)\ncoefs_multi  <- tidy(model_multi, conf.int = TRUE)\n\ncomparison <- tibble(\n  Variable = c(\"BMI (simple)\", \"BMI (adjusted)\"),\n  Estimate = c(coefs_simple$estimate[2], coefs_multi$estimate[2]),\n  `95% CI` = c(\n    paste0(round(coefs_simple$conf.low[2], 2), \" to \", round(coefs_simple$conf.high[2], 2)),\n    paste0(round(coefs_multi$conf.low[2], 2), \" to \", round(coefs_multi$conf.high[2], 2))\n  ),\n  p = c(format(coefs_simple$p.value[2], digits = 3),\n        format(coefs_multi$p.value[2], digits = 3))\n)\n\nkable(comparison, format = \"html\") %>%\n  kable_styling(full_width = FALSE, bootstrap_options = c(\"bordered\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-bordered\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Variable </th>\n   <th style=\"text-align:right;\"> Estimate </th>\n   <th style=\"text-align:left;\"> 95% CI </th>\n   <th style=\"text-align:left;\"> p </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> BMI (simple) </td>\n   <td style=\"text-align:right;\"> 1.928072 </td>\n   <td style=\"text-align:left;\"> 1.39 to 2.47 </td>\n   <td style=\"text-align:left;\"> 2.78e-11 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BMI (adjusted) </td>\n   <td style=\"text-align:right;\"> 2.014947 </td>\n   <td style=\"text-align:left;\"> 1.5 to 2.53 </td>\n   <td style=\"text-align:left;\"> 5.35e-13 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n:::{.callout-tip title=\"Reading Multiple Regression Output\"}\n- The BMI coefficient in the adjusted model tells you the effect of BMI *independent of* age and sex.\n- If the coefficient changes substantially after adjustment, **confounding was present**.\n- **Adjusted R²** penalises for the number of predictors and is more honest than raw R² for comparing models.\n:::\n\n---\n\n### 4.3 Adjusted R² and Model Comparison\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"Simple model R²:\", round(summary(model)$r.squared, 4),\n    \"| Adj R²:\", round(summary(model)$adj.r.squared, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple model R²: 0.201 | Adj R²: 0.197 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Multiple model R²:\", round(summary(model_multi)$r.squared, 4),\n    \"| Adj R²:\", round(summary(model_multi)$adj.r.squared, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMultiple model R²: 0.2857 | Adj R²: 0.2747 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nAdding age and sex explains an additional\",\n    round((summary(model_multi)$r.squared - summary(model)$r.squared) * 100, 1),\n    \"% of FBS variance.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAdding age and sex explains an additional 8.5 % of FBS variance.\n```\n\n\n:::\n:::\n\n\n:::{.callout-warning title=\"Overfitting\"}\nAdding more predictors always increases R² — even if the new variables are noise. **Adjusted R²** corrects for this. If adjusted R² drops when you add a variable, that variable is not improving the model.\n:::\n\n---\n\n## Section 5: Logistic Regression\n\n### 5.1 When the Outcome Is Binary\n\nWhat if the research question is: *\"Does higher BMI predict diabetes (yes/no)?\"*\n\nFBS is continuous — but diabetes status is **binary**. Linear regression can't model binary outcomes properly (it predicts values outside 0–1). We need **logistic regression**.\n\n**In words:** Logistic regression models the **log-odds** of the outcome:\n\n$$\\ln\\left(\\frac{p}{1-p}\\right) = \\beta_0 + \\beta_1 x$$\n\nwhere $p$ = probability of the event (diabetes = yes).\n\nThe **odds ratio** for a 1-unit increase in x is:\n\n$$OR = e^{\\beta_1}$$\n\n---\n\n### 5.2 Generating Binary Outcome Data\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Create diabetes outcome (higher BMI and age → higher probability)\nhealth$diabetes_prob <- plogis(-8 + 0.15 * health$BMI + 0.05 * health$Age)\nhealth$Diabetes <- rbinom(n, 1, health$diabetes_prob)\nhealth$Diabetes_label <- ifelse(health$Diabetes == 1, \"Diabetic\", \"Non-diabetic\")\n\ncat(\"Diabetes prevalence:\", round(mean(health$Diabetes) * 100, 1), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDiabetes prevalence: 13.5 %\n```\n\n\n:::\n:::\n\n\n---\n\n### 5.3 Fitting the Logistic Regression\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlogit_model <- glm(Diabetes ~ BMI + Age + Sex, data = health, family = binomial)\nsummary(logit_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Diabetes ~ BMI + Age + Sex, family = binomial, \n    data = health)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -7.88632    1.78488  -4.418 9.94e-06 ***\nBMI          0.15608    0.05142   3.035   0.0024 ** \nAge          0.04543    0.02000   2.271   0.0232 *  \nSexMale     -0.66062    0.44725  -1.477   0.1397    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 158.31  on 199  degrees of freedom\nResidual deviance: 141.55  on 196  degrees of freedom\nAIC: 149.55\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlogit_coefs <- tidy(logit_model, conf.int = TRUE, exponentiate = TRUE)\n\nor_table <- logit_coefs %>%\n  filter(term != \"(Intercept)\") %>%\n  select(Variable = term, OR = estimate, CI_low = conf.low, CI_high = conf.high,\n         p = p.value) %>%\n  mutate(across(c(OR, CI_low, CI_high), ~ round(., 3)),\n         p = format(p, digits = 3))\n\nkable(or_table, col.names = c(\"Variable\", \"OR\", \"95% CI Lower\", \"95% CI Upper\", \"p-value\"),\n      format = \"html\") %>%\n  kable_styling(full_width = FALSE, bootstrap_options = c(\"bordered\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-bordered table-hover\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Variable </th>\n   <th style=\"text-align:right;\"> OR </th>\n   <th style=\"text-align:right;\"> 95% CI Lower </th>\n   <th style=\"text-align:right;\"> 95% CI Upper </th>\n   <th style=\"text-align:left;\"> p-value </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> BMI </td>\n   <td style=\"text-align:right;\"> 1.169 </td>\n   <td style=\"text-align:right;\"> 1.060 </td>\n   <td style=\"text-align:right;\"> 1.299 </td>\n   <td style=\"text-align:left;\"> 0.0024 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Age </td>\n   <td style=\"text-align:right;\"> 1.046 </td>\n   <td style=\"text-align:right;\"> 1.007 </td>\n   <td style=\"text-align:right;\"> 1.090 </td>\n   <td style=\"text-align:left;\"> 0.0232 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SexMale </td>\n   <td style=\"text-align:right;\"> 0.517 </td>\n   <td style=\"text-align:right;\"> 0.208 </td>\n   <td style=\"text-align:right;\"> 1.220 </td>\n   <td style=\"text-align:left;\"> 0.1397 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n:::{.callout-note title=\"Interpreting Logistic Regression ORs\"}\n- **OR for BMI:** For each 1 kg/m² increase in BMI, the odds of diabetes change by a factor of 1.17 (holding age and sex constant).\n- **OR > 1:** Higher BMI increases the odds of diabetes.\n- **OR < 1:** The variable is protective.\n- **95% CI excluding 1.0:** Statistically significant.\n\nThis connects directly to the Odds Ratio from Module 10 — logistic regression is the **multivariable extension** of the 2×2 table OR.\n:::\n\n---\n\n### 5.4 Predicted Probabilities\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbmi_seq <- data.frame(BMI = seq(16, 40, by = 0.5), Age = 45, Sex = \"Male\")\nbmi_seq$pred_prob <- predict(logit_model, newdata = bmi_seq, type = \"response\")\n\nggplot(bmi_seq, aes(x = BMI, y = pred_prob)) +\n  geom_line(color = \"#e74c3c\", linewidth = 1.2) +\n  geom_rug(data = health %>% filter(Diabetes == 1), aes(x = BMI, y = NULL),\n           sides = \"t\", alpha = 0.3, color = \"#e74c3c\") +\n  geom_rug(data = health %>% filter(Diabetes == 0), aes(x = BMI, y = NULL),\n           sides = \"b\", alpha = 0.3, color = \"#2ecc71\") +\n  geom_hline(yintercept = 0.5, linetype = \"dashed\", color = \"gray50\") +\n  annotate(\"text\", x = 37, y = 0.52, label = \"50% threshold\",\n           color = \"gray50\", fontface = \"italic\") +\n  scale_y_continuous(labels = percent_format(), limits = c(0, 1)) +\n  labs(title = \"Predicted Probability of Diabetes by BMI\",\n       subtitle = \"Logistic regression (Age = 45, Male) | Rug marks = actual cases\",\n       x = \"BMI (kg/m²)\", y = \"Predicted probability of diabetes\") +\n  theme_clean()\n```\n\n::: {.cell-output-display}\n![](11-correlation-regression_files/figure-html/predicted-probs-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThe S-shaped (sigmoid) curve is the hallmark of logistic regression. The probability is bounded between 0 and 1 — unlike linear regression, which would predict impossible values.\n\n---\n\n## Section 6: The Correlation–Causation–Regression Framework\n\n:::{.callout-important title=\"Correlation → Regression → Causation?\"}\n| Tool | What it tells you | What it does NOT tell you |\n|------|-------------------|--------------------------|\n| Correlation (r) | Strength and direction of linear association | Whether x causes y |\n| Simple regression | How y changes per unit of x; prediction | Whether the relationship is causal |\n| Multiple regression | Effect of x *adjusted for confounders* | Whether all confounders are measured |\n| Logistic regression | OR for binary outcomes, adjusted | Causation without proper study design |\n\n**Regression adjusts for measured confounders** — but unmeasured confounders can still bias results. Only a well-designed **RCT** (Module 7) can establish causation. Regression in observational data provides *adjusted associations*, not proof of causation.\n:::\n\n---\n\n## Section 7: Decision Framework\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-bordered table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;font-weight: bold;color: white !important;background-color: rgba(30, 58, 95, 255) !important;\"> Scenario </th>\n   <th style=\"text-align:left;font-weight: bold;color: white !important;background-color: rgba(30, 58, 95, 255) !important;\"> Method </th>\n   <th style=\"text-align:left;font-weight: bold;color: white !important;background-color: rgba(30, 58, 95, 255) !important;\"> Output </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;width: 40%; font-weight: bold;\"> Two continuous variables — strength of association? </td>\n   <td style=\"text-align:left;\"> Pearson correlation (r) </td>\n   <td style=\"text-align:left;\"> r, p-value, 95% CI </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 40%; font-weight: bold;\"> Ordinal data or outliers present? </td>\n   <td style=\"text-align:left;\"> Spearman rank correlation (rₛ) </td>\n   <td style=\"text-align:left;\"> rₛ, p-value </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 40%; font-weight: bold;\"> Predict continuous outcome from one predictor? </td>\n   <td style=\"text-align:left;\"> Simple linear regression </td>\n   <td style=\"text-align:left;\"> Slope, R², equation, CI/PI </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 40%; font-weight: bold;\"> Predict continuous outcome, adjust for confounders? </td>\n   <td style=\"text-align:left;\"> Multiple linear regression </td>\n   <td style=\"text-align:left;\"> Adjusted slopes, adjusted R² </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 40%; font-weight: bold;\"> Predict binary outcome (yes/no)? </td>\n   <td style=\"text-align:left;\"> Logistic regression </td>\n   <td style=\"text-align:left;\"> Odds ratios, predicted probabilities </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 40%; font-weight: bold;\"> Predict time-to-event (survival)? </td>\n   <td style=\"text-align:left;\"> Cox regression (Module 12) </td>\n   <td style=\"text-align:left;\"> Hazard ratios </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n---\n\n## Summary\n\n:::{.callout-tip title=\"Key Takeaways\"}\n1. **Pearson r** measures linear association (−1 to +1). **Spearman rₛ** is the rank-based alternative for ordinal or skewed data.\n\n2. **Correlation ≠ causation.** Confounding, reverse causality, and selection bias can create spurious associations.\n\n3. **Simple linear regression** fits y = β₀ + β₁x. The slope is the change in y per 1-unit increase in x. R² = fraction of variance explained.\n\n4. **Always check LINE assumptions** — linearity, independence, normality of residuals, equal variance. Use diagnostic plots.\n\n5. **Confidence intervals** (for the mean) are narrower than **prediction intervals** (for a new individual). Always report uncertainty.\n\n6. **Multiple regression** adjusts for confounders: \"effect of x₁ holding x₂, x₃, ... constant.\" Use adjusted R² for model comparison.\n\n7. **Logistic regression** models binary outcomes. Coefficients exponentiate to **odds ratios** — connecting directly to Module 10.\n\n8. **No regression model proves causation** in observational data. Regression adjusts for *measured* confounders; RCTs are needed for causal claims.\n:::\n\n---\n\n## Practice Questions\n\n### Q1: Correlation vs Causation\n\n\n::: {.cell layout-align=\"center\"}\n<div class=\"mcq-container\" id=\"mcq-m11q1\">\n<div class=\"mcq-question\"><strong>A study finds r = 0.85 between hours of TV watched per day and BMI in 500 adults. Which interpretation is MOST appropriate?</strong></div>\n<div class=\"mcq-options\">\n<label class=\"mcq-option\" id=\"m11q1-opt-A\"><input type=\"radio\" name=\"m11q1\" value=\"A\"> <span class=\"mcq-letter\">A.</span> Watching more TV causes weight gain</label>\n<label class=\"mcq-option\" id=\"m11q1-opt-B\"><input type=\"radio\" name=\"m11q1\" value=\"B\"> <span class=\"mcq-letter\">B.</span> There is a strong positive linear association between TV hours and BMI</label>\n<label class=\"mcq-option\" id=\"m11q1-opt-C\"><input type=\"radio\" name=\"m11q1\" value=\"C\"> <span class=\"mcq-letter\">C.</span> 85% of the variation in BMI is explained by TV watching</label>\n<label class=\"mcq-option\" id=\"m11q1-opt-D\"><input type=\"radio\" name=\"m11q1\" value=\"D\"> <span class=\"mcq-letter\">D.</span> The relationship is statistically significant but clinically irrelevant</label>\n</div>\n<button class=\"mcq-check-btn\" onclick=\"checkMCQ_m11q1()\">Check Answer</button>\n<div class=\"mcq-feedback\" id=\"m11q1-feedback\" style=\"display:none;\"></div>\n<div class=\"mcq-explanation\" id=\"m11q1-explanation\" style=\"display:none;\">\n<div class=\"mcq-expl-wrong\"><strong>&#10008; A. Watching more TV causes weight gain</strong> &mdash; Incorrect. Correlation does not establish causation — confounders like sedentary lifestyle, diet, and socioeconomic status may explain the association.</div>\n<div class=\"mcq-expl-correct\"><strong>&#10004; B. There is a strong positive linear association between TV hours and BMI</strong> &mdash; Correct! r = 0.85 indicates a strong positive linear association. We cannot infer causation from correlation alone.</div>\n<div class=\"mcq-expl-wrong\"><strong>&#10008; C. 85% of the variation in BMI is explained by TV watching</strong> &mdash; Incorrect. R² (not r) gives the proportion of variance explained. R² = 0.85² = 0.72, meaning 72% — but this still doesn't prove causation.</div>\n<div class=\"mcq-expl-wrong\"><strong>&#10008; D. The relationship is statistically significant but clinically irrelevant</strong> &mdash; Incorrect. r = 0.85 is both statistically and practically strong. Clinical relevance cannot be dismissed without context.</div>\n</div>\n</div>\n<script>\nfunction checkMCQ_m11q1() {\nvar radios = document.getElementsByName(\"m11q1\");\nvar selected = null;\nfor (var i = 0; i < radios.length; i++) {\nif (radios[i].checked) { selected = radios[i].value; break; }\n}\nif (!selected) {\nvar fb = document.getElementById(\"m11q1-feedback\");\nfb.style.display = \"block\";\nfb.className = \"mcq-feedback mcq-feedback-warn\";\nfb.innerHTML = \"Please select an option before checking.\";\nreturn;\n}\nvar correct = \"B\";\nvar fb = document.getElementById(\"m11q1-feedback\");\nvar expl = document.getElementById(\"m11q1-explanation\");\nfb.style.display = \"block\";\nexpl.style.display = \"block\";\nfor (var i = 0; i < radios.length; i++) { radios[i].disabled = true; }\ndocument.querySelector(\"#mcq-m11q1 .mcq-check-btn\").disabled = true;\nvar opts = document.querySelectorAll(\"#mcq-m11q1 .mcq-option\");\nfor (var i = 0; i < opts.length; i++) {\nvar val = opts[i].querySelector(\"input\").value;\nif (val === correct) { opts[i].classList.add(\"mcq-correct\"); }\nelse if (val === selected) { opts[i].classList.add(\"mcq-wrong\"); }\n}\nif (selected === correct) {\nfb.className = \"mcq-feedback mcq-feedback-correct\";\nfb.innerHTML = \"&#10004; Correct!\";\n} else {\nfb.className = \"mcq-feedback mcq-feedback-wrong\";\nfb.innerHTML = \"&#10008; Incorrect. The correct answer is \" + correct + \".\";\n}\n}\n</script>\n:::\n\n\n---\n\n### Q2: Regression Prediction\n\n\n::: {.cell layout-align=\"center\"}\n<div class=\"mcq-container\" id=\"mcq-m11q2\">\n<div class=\"mcq-question\"><strong>A regression model gives: SBP = 90 + 0.6 × Age (years). For a 60-year-old patient, what is the predicted systolic BP?</strong></div>\n<div class=\"mcq-options\">\n<label class=\"mcq-option\" id=\"m11q2-opt-A\"><input type=\"radio\" name=\"m11q2\" value=\"A\"> <span class=\"mcq-letter\">A.</span> 90 mmHg</label>\n<label class=\"mcq-option\" id=\"m11q2-opt-B\"><input type=\"radio\" name=\"m11q2\" value=\"B\"> <span class=\"mcq-letter\">B.</span> 126 mmHg</label>\n<label class=\"mcq-option\" id=\"m11q2-opt-C\"><input type=\"radio\" name=\"m11q2\" value=\"C\"> <span class=\"mcq-letter\">C.</span> 150 mmHg</label>\n<label class=\"mcq-option\" id=\"m11q2-opt-D\"><input type=\"radio\" name=\"m11q2\" value=\"D\"> <span class=\"mcq-letter\">D.</span> 36 mmHg</label>\n</div>\n<button class=\"mcq-check-btn\" onclick=\"checkMCQ_m11q2()\">Check Answer</button>\n<div class=\"mcq-feedback\" id=\"m11q2-feedback\" style=\"display:none;\"></div>\n<div class=\"mcq-explanation\" id=\"m11q2-explanation\" style=\"display:none;\">\n<div class=\"mcq-expl-wrong\"><strong>&#10008; A. 90 mmHg</strong> &mdash; Incorrect. That is the intercept only — you need to add the age contribution: 0.6 × 60 = 36.</div>\n<div class=\"mcq-expl-correct\"><strong>&#10004; B. 126 mmHg</strong> &mdash; Correct! SBP = 90 + 0.6 × 60 = 90 + 36 = 126 mmHg.</div>\n<div class=\"mcq-expl-wrong\"><strong>&#10008; C. 150 mmHg</strong> &mdash; Incorrect. Check the arithmetic: 90 + (0.6 × 60) = 126, not 150.</div>\n<div class=\"mcq-expl-wrong\"><strong>&#10008; D. 36 mmHg</strong> &mdash; Incorrect. 36 is the age contribution (0.6 × 60), but you must add the intercept (90).</div>\n</div>\n</div>\n<script>\nfunction checkMCQ_m11q2() {\nvar radios = document.getElementsByName(\"m11q2\");\nvar selected = null;\nfor (var i = 0; i < radios.length; i++) {\nif (radios[i].checked) { selected = radios[i].value; break; }\n}\nif (!selected) {\nvar fb = document.getElementById(\"m11q2-feedback\");\nfb.style.display = \"block\";\nfb.className = \"mcq-feedback mcq-feedback-warn\";\nfb.innerHTML = \"Please select an option before checking.\";\nreturn;\n}\nvar correct = \"B\";\nvar fb = document.getElementById(\"m11q2-feedback\");\nvar expl = document.getElementById(\"m11q2-explanation\");\nfb.style.display = \"block\";\nexpl.style.display = \"block\";\nfor (var i = 0; i < radios.length; i++) { radios[i].disabled = true; }\ndocument.querySelector(\"#mcq-m11q2 .mcq-check-btn\").disabled = true;\nvar opts = document.querySelectorAll(\"#mcq-m11q2 .mcq-option\");\nfor (var i = 0; i < opts.length; i++) {\nvar val = opts[i].querySelector(\"input\").value;\nif (val === correct) { opts[i].classList.add(\"mcq-correct\"); }\nelse if (val === selected) { opts[i].classList.add(\"mcq-wrong\"); }\n}\nif (selected === correct) {\nfb.className = \"mcq-feedback mcq-feedback-correct\";\nfb.innerHTML = \"&#10004; Correct!\";\n} else {\nfb.className = \"mcq-feedback mcq-feedback-wrong\";\nfb.innerHTML = \"&#10008; Incorrect. The correct answer is \" + correct + \".\";\n}\n}\n</script>\n:::\n\n\n---\n\n### Q3: R-Squared Interpretation\n\n\n::: {.cell layout-align=\"center\"}\n<div class=\"mcq-container\" id=\"mcq-m11q3\">\n<div class=\"mcq-question\"><strong>In a simple linear regression, R² = 0.64. Which statement is correct?</strong></div>\n<div class=\"mcq-options\">\n<label class=\"mcq-option\" id=\"m11q3-opt-A\"><input type=\"radio\" name=\"m11q3\" value=\"A\"> <span class=\"mcq-letter\">A.</span> The correlation coefficient r = 0.64</label>\n<label class=\"mcq-option\" id=\"m11q3-opt-B\"><input type=\"radio\" name=\"m11q3\" value=\"B\"> <span class=\"mcq-letter\">B.</span> The predictor explains 64% of the variation in the outcome</label>\n<label class=\"mcq-option\" id=\"m11q3-opt-C\"><input type=\"radio\" name=\"m11q3\" value=\"C\"> <span class=\"mcq-letter\">C.</span> The model correctly classifies 64% of observations</label>\n<label class=\"mcq-option\" id=\"m11q3-opt-D\"><input type=\"radio\" name=\"m11q3\" value=\"D\"> <span class=\"mcq-letter\">D.</span> The slope of the regression line is 0.64</label>\n</div>\n<button class=\"mcq-check-btn\" onclick=\"checkMCQ_m11q3()\">Check Answer</button>\n<div class=\"mcq-feedback\" id=\"m11q3-feedback\" style=\"display:none;\"></div>\n<div class=\"mcq-explanation\" id=\"m11q3-explanation\" style=\"display:none;\">\n<div class=\"mcq-expl-wrong\"><strong>&#10008; A. The correlation coefficient r = 0.64</strong> &mdash; Incorrect. R² = r², so r = √0.64 = 0.80 (assuming positive association).</div>\n<div class=\"mcq-expl-correct\"><strong>&#10004; B. The predictor explains 64% of the variation in the outcome</strong> &mdash; Correct! R² = 0.64 means 64% of outcome variance is explained by the model. The remaining 36% is unexplained.</div>\n<div class=\"mcq-expl-wrong\"><strong>&#10008; C. The model correctly classifies 64% of observations</strong> &mdash; Incorrect. R² is not a classification metric — it measures proportion of variance explained.</div>\n<div class=\"mcq-expl-wrong\"><strong>&#10008; D. The slope of the regression line is 0.64</strong> &mdash; Incorrect. R² and the slope are different quantities. The slope depends on the units of x and y.</div>\n</div>\n</div>\n<script>\nfunction checkMCQ_m11q3() {\nvar radios = document.getElementsByName(\"m11q3\");\nvar selected = null;\nfor (var i = 0; i < radios.length; i++) {\nif (radios[i].checked) { selected = radios[i].value; break; }\n}\nif (!selected) {\nvar fb = document.getElementById(\"m11q3-feedback\");\nfb.style.display = \"block\";\nfb.className = \"mcq-feedback mcq-feedback-warn\";\nfb.innerHTML = \"Please select an option before checking.\";\nreturn;\n}\nvar correct = \"B\";\nvar fb = document.getElementById(\"m11q3-feedback\");\nvar expl = document.getElementById(\"m11q3-explanation\");\nfb.style.display = \"block\";\nexpl.style.display = \"block\";\nfor (var i = 0; i < radios.length; i++) { radios[i].disabled = true; }\ndocument.querySelector(\"#mcq-m11q3 .mcq-check-btn\").disabled = true;\nvar opts = document.querySelectorAll(\"#mcq-m11q3 .mcq-option\");\nfor (var i = 0; i < opts.length; i++) {\nvar val = opts[i].querySelector(\"input\").value;\nif (val === correct) { opts[i].classList.add(\"mcq-correct\"); }\nelse if (val === selected) { opts[i].classList.add(\"mcq-wrong\"); }\n}\nif (selected === correct) {\nfb.className = \"mcq-feedback mcq-feedback-correct\";\nfb.innerHTML = \"&#10004; Correct!\";\n} else {\nfb.className = \"mcq-feedback mcq-feedback-wrong\";\nfb.innerHTML = \"&#10008; Incorrect. The correct answer is \" + correct + \".\";\n}\n}\n</script>\n:::\n\n\n---\n\n### Q4: Logistic Regression OR\n\n\n::: {.cell layout-align=\"center\"}\n<div class=\"mcq-container\" id=\"mcq-m11q4\">\n<div class=\"mcq-question\"><strong>A logistic regression for diabetes (yes/no) gives OR = 1.12 (95% CI: 1.04–1.21) for BMI. What is the correct interpretation?</strong></div>\n<div class=\"mcq-options\">\n<label class=\"mcq-option\" id=\"m11q4-opt-A\"><input type=\"radio\" name=\"m11q4\" value=\"A\"> <span class=\"mcq-letter\">A.</span> For each 1 kg/m² increase in BMI, the probability of diabetes increases by 12%</label>\n<label class=\"mcq-option\" id=\"m11q4-opt-B\"><input type=\"radio\" name=\"m11q4\" value=\"B\"> <span class=\"mcq-letter\">B.</span> For each 1 kg/m² increase in BMI, the odds of diabetes increase by 12%, and this is statistically significant</label>\n<label class=\"mcq-option\" id=\"m11q4-opt-C\"><input type=\"radio\" name=\"m11q4\" value=\"C\"> <span class=\"mcq-letter\">C.</span> BMI causes diabetes with 12% certainty</label>\n<label class=\"mcq-option\" id=\"m11q4-opt-D\"><input type=\"radio\" name=\"m11q4\" value=\"D\"> <span class=\"mcq-letter\">D.</span> The model explains 12% of the variance in diabetes</label>\n</div>\n<button class=\"mcq-check-btn\" onclick=\"checkMCQ_m11q4()\">Check Answer</button>\n<div class=\"mcq-feedback\" id=\"m11q4-feedback\" style=\"display:none;\"></div>\n<div class=\"mcq-explanation\" id=\"m11q4-explanation\" style=\"display:none;\">\n<div class=\"mcq-expl-wrong\"><strong>&#10008; A. For each 1 kg/m² increase in BMI, the probability of diabetes increases by 12%</strong> &mdash; Incorrect. OR is not the same as probability increase. The OR says the odds multiply by 1.12 per unit BMI increase.</div>\n<div class=\"mcq-expl-correct\"><strong>&#10004; B. For each 1 kg/m² increase in BMI, the odds of diabetes increase by 12%, and this is statistically significant</strong> &mdash; Correct! OR = 1.12 means the odds multiply by 1.12 per unit BMI increase (12% increase). The CI excludes 1.0, so p < 0.05.</div>\n<div class=\"mcq-expl-wrong\"><strong>&#10008; C. BMI causes diabetes with 12% certainty</strong> &mdash; Incorrect. An OR does not express certainty of causation. It quantifies the association between BMI and odds of diabetes.</div>\n<div class=\"mcq-expl-wrong\"><strong>&#10008; D. The model explains 12% of the variance in diabetes</strong> &mdash; Incorrect. OR is not R². The 1.12 refers to the odds ratio per unit change in the predictor.</div>\n</div>\n</div>\n<script>\nfunction checkMCQ_m11q4() {\nvar radios = document.getElementsByName(\"m11q4\");\nvar selected = null;\nfor (var i = 0; i < radios.length; i++) {\nif (radios[i].checked) { selected = radios[i].value; break; }\n}\nif (!selected) {\nvar fb = document.getElementById(\"m11q4-feedback\");\nfb.style.display = \"block\";\nfb.className = \"mcq-feedback mcq-feedback-warn\";\nfb.innerHTML = \"Please select an option before checking.\";\nreturn;\n}\nvar correct = \"B\";\nvar fb = document.getElementById(\"m11q4-feedback\");\nvar expl = document.getElementById(\"m11q4-explanation\");\nfb.style.display = \"block\";\nexpl.style.display = \"block\";\nfor (var i = 0; i < radios.length; i++) { radios[i].disabled = true; }\ndocument.querySelector(\"#mcq-m11q4 .mcq-check-btn\").disabled = true;\nvar opts = document.querySelectorAll(\"#mcq-m11q4 .mcq-option\");\nfor (var i = 0; i < opts.length; i++) {\nvar val = opts[i].querySelector(\"input\").value;\nif (val === correct) { opts[i].classList.add(\"mcq-correct\"); }\nelse if (val === selected) { opts[i].classList.add(\"mcq-wrong\"); }\n}\nif (selected === correct) {\nfb.className = \"mcq-feedback mcq-feedback-correct\";\nfb.innerHTML = \"&#10004; Correct!\";\n} else {\nfb.className = \"mcq-feedback mcq-feedback-wrong\";\nfb.innerHTML = \"&#10008; Incorrect. The correct answer is \" + correct + \".\";\n}\n}\n</script>\n:::\n\n\n---\n\n### Q5: Regression Assumptions\n\n\n::: {.cell layout-align=\"center\"}\n<div class=\"mcq-container\" id=\"mcq-m11q5\">\n<div class=\"mcq-question\"><strong>Which of the following is NOT an assumption of simple linear regression?</strong></div>\n<div class=\"mcq-options\">\n<label class=\"mcq-option\" id=\"m11q5-opt-A\"><input type=\"radio\" name=\"m11q5\" value=\"A\"> <span class=\"mcq-letter\">A.</span> Linearity of the relationship between x and y</label>\n<label class=\"mcq-option\" id=\"m11q5-opt-B\"><input type=\"radio\" name=\"m11q5\" value=\"B\"> <span class=\"mcq-letter\">B.</span> Independence of observations</label>\n<label class=\"mcq-option\" id=\"m11q5-opt-C\"><input type=\"radio\" name=\"m11q5\" value=\"C\"> <span class=\"mcq-letter\">C.</span> The predictor variable x must be normally distributed</label>\n<label class=\"mcq-option\" id=\"m11q5-opt-D\"><input type=\"radio\" name=\"m11q5\" value=\"D\"> <span class=\"mcq-letter\">D.</span> Homoscedasticity (constant variance of residuals)</label>\n</div>\n<button class=\"mcq-check-btn\" onclick=\"checkMCQ_m11q5()\">Check Answer</button>\n<div class=\"mcq-feedback\" id=\"m11q5-feedback\" style=\"display:none;\"></div>\n<div class=\"mcq-explanation\" id=\"m11q5-explanation\" style=\"display:none;\">\n<div class=\"mcq-expl-wrong\"><strong>&#10008; A. Linearity of the relationship between x and y</strong> &mdash; Incorrect — this IS a required assumption (the L in LINE).</div>\n<div class=\"mcq-expl-wrong\"><strong>&#10008; B. Independence of observations</strong> &mdash; Incorrect — this IS a required assumption (the I in LINE).</div>\n<div class=\"mcq-expl-correct\"><strong>&#10004; C. The predictor variable x must be normally distributed</strong> &mdash; Correct! Regression assumes normality of *residuals*, not of x. The predictor can have any distribution.</div>\n<div class=\"mcq-expl-wrong\"><strong>&#10008; D. Homoscedasticity (constant variance of residuals)</strong> &mdash; Incorrect — this IS a required assumption (the E in LINE).</div>\n</div>\n</div>\n<script>\nfunction checkMCQ_m11q5() {\nvar radios = document.getElementsByName(\"m11q5\");\nvar selected = null;\nfor (var i = 0; i < radios.length; i++) {\nif (radios[i].checked) { selected = radios[i].value; break; }\n}\nif (!selected) {\nvar fb = document.getElementById(\"m11q5-feedback\");\nfb.style.display = \"block\";\nfb.className = \"mcq-feedback mcq-feedback-warn\";\nfb.innerHTML = \"Please select an option before checking.\";\nreturn;\n}\nvar correct = \"C\";\nvar fb = document.getElementById(\"m11q5-feedback\");\nvar expl = document.getElementById(\"m11q5-explanation\");\nfb.style.display = \"block\";\nexpl.style.display = \"block\";\nfor (var i = 0; i < radios.length; i++) { radios[i].disabled = true; }\ndocument.querySelector(\"#mcq-m11q5 .mcq-check-btn\").disabled = true;\nvar opts = document.querySelectorAll(\"#mcq-m11q5 .mcq-option\");\nfor (var i = 0; i < opts.length; i++) {\nvar val = opts[i].querySelector(\"input\").value;\nif (val === correct) { opts[i].classList.add(\"mcq-correct\"); }\nelse if (val === selected) { opts[i].classList.add(\"mcq-wrong\"); }\n}\nif (selected === correct) {\nfb.className = \"mcq-feedback mcq-feedback-correct\";\nfb.innerHTML = \"&#10004; Correct!\";\n} else {\nfb.className = \"mcq-feedback mcq-feedback-wrong\";\nfb.innerHTML = \"&#10008; Incorrect. The correct answer is \" + correct + \".\";\n}\n}\n</script>\n:::\n\n\n---\n\n### Q6: Confounding in Multiple Regression\n\n\n::: {.cell layout-align=\"center\"}\n<div class=\"mcq-container\" id=\"mcq-m11q6\">\n<div class=\"mcq-question\"><strong>A multiple regression shows that the association between BMI and FBS drops from β = 2.1 (simple) to β = 1.4 (after adjusting for age and sex). What does this suggest?</strong></div>\n<div class=\"mcq-options\">\n<label class=\"mcq-option\" id=\"m11q6-opt-A\"><input type=\"radio\" name=\"m11q6\" value=\"A\"> <span class=\"mcq-letter\">A.</span> The original association was entirely spurious</label>\n<label class=\"mcq-option\" id=\"m11q6-opt-B\"><input type=\"radio\" name=\"m11q6\" value=\"B\"> <span class=\"mcq-letter\">B.</span> Age and sex are mediators in the causal pathway</label>\n<label class=\"mcq-option\" id=\"m11q6-opt-C\"><input type=\"radio\" name=\"m11q6\" value=\"C\"> <span class=\"mcq-letter\">C.</span> Age and/or sex were confounders — they partly explained the BMI–FBS association</label>\n<label class=\"mcq-option\" id=\"m11q6-opt-D\"><input type=\"radio\" name=\"m11q6\" value=\"D\"> <span class=\"mcq-letter\">D.</span> The multiple regression model is invalid</label>\n</div>\n<button class=\"mcq-check-btn\" onclick=\"checkMCQ_m11q6()\">Check Answer</button>\n<div class=\"mcq-feedback\" id=\"m11q6-feedback\" style=\"display:none;\"></div>\n<div class=\"mcq-explanation\" id=\"m11q6-explanation\" style=\"display:none;\">\n<div class=\"mcq-expl-wrong\"><strong>&#10008; A. The original association was entirely spurious</strong> &mdash; Incorrect. The adjusted coefficient is still 1.4 and presumably still significant — the association remains, just weaker.</div>\n<div class=\"mcq-expl-wrong\"><strong>&#10008; B. Age and sex are mediators in the causal pathway</strong> &mdash; Incorrect. Without a causal diagram, we cannot distinguish confounding from mediation based on coefficient change alone.</div>\n<div class=\"mcq-expl-correct\"><strong>&#10004; C. Age and/or sex were confounders — they partly explained the BMI–FBS association</strong> &mdash; Correct! The coefficient dropped by ~33% after adjustment, suggesting age/sex confounded part (but not all) of the association.</div>\n<div class=\"mcq-expl-wrong\"><strong>&#10008; D. The multiple regression model is invalid</strong> &mdash; Incorrect. A coefficient change after adjustment is expected and informative — it means confounding was present and has been partially addressed.</div>\n</div>\n</div>\n<script>\nfunction checkMCQ_m11q6() {\nvar radios = document.getElementsByName(\"m11q6\");\nvar selected = null;\nfor (var i = 0; i < radios.length; i++) {\nif (radios[i].checked) { selected = radios[i].value; break; }\n}\nif (!selected) {\nvar fb = document.getElementById(\"m11q6-feedback\");\nfb.style.display = \"block\";\nfb.className = \"mcq-feedback mcq-feedback-warn\";\nfb.innerHTML = \"Please select an option before checking.\";\nreturn;\n}\nvar correct = \"C\";\nvar fb = document.getElementById(\"m11q6-feedback\");\nvar expl = document.getElementById(\"m11q6-explanation\");\nfb.style.display = \"block\";\nexpl.style.display = \"block\";\nfor (var i = 0; i < radios.length; i++) { radios[i].disabled = true; }\ndocument.querySelector(\"#mcq-m11q6 .mcq-check-btn\").disabled = true;\nvar opts = document.querySelectorAll(\"#mcq-m11q6 .mcq-option\");\nfor (var i = 0; i < opts.length; i++) {\nvar val = opts[i].querySelector(\"input\").value;\nif (val === correct) { opts[i].classList.add(\"mcq-correct\"); }\nelse if (val === selected) { opts[i].classList.add(\"mcq-wrong\"); }\n}\nif (selected === correct) {\nfb.className = \"mcq-feedback mcq-feedback-correct\";\nfb.innerHTML = \"&#10004; Correct!\";\n} else {\nfb.className = \"mcq-feedback mcq-feedback-wrong\";\nfb.innerHTML = \"&#10008; Incorrect. The correct answer is \" + correct + \".\";\n}\n}\n</script>\n:::\n\n\n---\n\n## Appendix: R Functions Quick Reference\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ======================================\n# QUICK R REFERENCE — CORRELATION & REGRESSION\n# ======================================\n\n# Pearson correlation\ncor(x, y)\ncor.test(x, y)  # with p-value and 95% CI\n\n# Spearman correlation\ncor(x, y, method = \"spearman\")\n\n# Simple linear regression\nmodel <- lm(y ~ x, data = df)\nsummary(model)                       # coefficients, R², p-values\nconfint(model)                       # 95% CI for coefficients\npredict(model, newdata, interval = \"confidence\")  # CI for mean\npredict(model, newdata, interval = \"prediction\")  # PI for individual\n\n# Diagnostic plots\npar(mfrow = c(2,2)); plot(model)\n\n# Multiple regression\nmodel_multi <- lm(y ~ x1 + x2 + x3, data = df)\nsummary(model_multi)\n\n# Logistic regression\nlogit <- glm(y ~ x1 + x2, data = df, family = binomial)\nsummary(logit)\nexp(coef(logit))          # odds ratios\nexp(confint(logit))       # 95% CI for ORs\npredict(logit, type = \"response\")  # predicted probabilities\n\n# Compare models\nanova(model_simple, model_multi)\nAIC(model_simple, model_multi)\n```\n:::\n\n\n---\n\n**End of Module 11**\n\n*AIIMS Bhopal Biostatistics Course | Updated: 2026-02-25*\n",
    "supporting": [
      "11-correlation-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}